services:
    postgres:
        # Runs on default port 5432
        build: postgres/.
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - "5432:5432"

    adminer:
        image: michalhosna/adminer
        ports:
            - 8001:8080
        environment:
            ADMINER_DRIVER: pgsql
            ADMINER_SERVER: postgres
            ADMINER_USERNAME: ${POSTGRES_USER}
            ADMINER_PASSWORD: ${POSTGRES_PASSWORD}
            ADMINER_DB: ${POSTGRES_DB}
            ADMINER_AUTOLOGIN: 1
            ADMINER_NAME: BookBarter Adminer
        depends_on:
            - postgres
